vich_uploader:
    db_driver: orm
    mappings:
        tracks:
            uri_prefix: /uploads/tracks
            upload_destination: '%kernel.project_dir%/public/uploads/tracks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
